/**
 * 创建/编辑播客表单组件 - MUI 版本
 */

'use client';

import { useForm, Controller } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useEffect, useRef, useState } from 'react';
import type { Podcast } from '@/lib/types';
import { podcastsAPI } from '@/lib/api/client';
import { chineseToPinyin } from '@/lib/utils/pinyin';
import { showAlert, showConfirm } from '@/lib/stores/dialog';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import FormControl from '@mui/material/FormControl';
import InputLabel from '@mui/material/InputLabel';
import Select from '@mui/material/Select';
import MenuItem from '@mui/material/MenuItem';
import FormControlLabel from '@mui/material/FormControlLabel';
import Checkbox from '@mui/material/Checkbox';
import Alert from '@mui/material/Alert';
import CircularProgress from '@mui/material/CircularProgress';
import Image from '@mui/icons-material/Image';
import Delete from '@mui/icons-material/Delete';
import AutoAwesome from '@mui/icons-material/AutoAwesome';

const podcastSchema = z.object({
  dirName: z
    .string()
    .min(1, '目录名称不能为空')
    .regex(/^[a-zA-Z0-9_-]+$/, '目录名称只能包含字母、数字、下划线和连字符'),
  title: z.string().min(1, '播客标题不能为空'),
  description: z.string().optional(),
  author: z.string().optional(),
  email: z.union([z.string().email('邮箱格式不正确'), z.literal('')]).optional(),
  category: z.string().optional(),
  language: z.string().optional(),
  explicit: z.boolean().optional(),
});

type PodcastFormData = z.infer<typeof podcastSchema>;

interface PodcastFormProps {
  podcast?: Podcast | null;
  onSuccess?: () => void;
  onCancel?: () => void;
}

export default function PodcastForm({ podcast, onSuccess, onCancel }: PodcastFormProps) {
  const isEditing = !!podcast;
  const titleManuallyEditedRef = useRef(false);
  const [isUploadingCover, setIsUploadingCover] = useState(false);
  const [coverUploadError, setCoverUploadError] = useState('');

  const {
    register,
    handleSubmit,
    control,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<PodcastFormData>({
    resolver: zodResolver(podcastSchema),
    defaultValues: podcast
      ? {
          dirName: podcast.dirName,
          title: podcast.title,
          description: podcast.description || '',
          author: podcast.author || '',
          email: podcast.email || '',
          category: podcast.category || 'Technology',
          language: podcast.language || 'zh-CN',
          explicit: podcast.explicit || false,
        }
      : {
          dirName: '',
          title: '',
          description: '',
          author: '',
          email: '',
          category: 'Technology',
          language: 'zh-CN',
          explicit: false,
        },
  });

  const dirName = watch('dirName');
  const title = watch('title');

  // 当目录名称变化时，自动更新标题
  useEffect(() => {
    if (!isEditing && !titleManuallyEditedRef.current && dirName) {
      const formattedTitle = dirName
        .split(/[-_]/)
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
      setValue('title', formattedTitle);
    }
  }, [dirName, isEditing, setValue]);

  // 监听标题的手动修改
  const handleTitleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    titleManuallyEditedRef.current = true;
    setValue('title', e.target.value);
  };

  // 自动生成 dirName
  const handleAutoGenerateDirName = () => {
    const currentTitle = watch('title');
    if (currentTitle) {
      const generatedDirName = chineseToPinyin(currentTitle);
      setValue('dirName', generatedDirName || `podcast-${Date.now()}`);
    }
  };

  // 上传封面
  const handleCoverUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!isEditing || !podcast) return;

    const file = e.target.files?.[0];
    if (!file) return;

    setIsUploadingCover(true);
    setCoverUploadError('');

    try {
      const response = await podcastsAPI.uploadCover(podcast.username, podcast.dirName, file);

      if (response.status === 'success') {
        onSuccess?.();
      } else {
        const errorMsg = response.status === 'error' ? response.message : '上传失败';
        setCoverUploadError(errorMsg);
      }
    } catch (error) {
      console.error('[PodcastForm] Cover upload error:', error);
      setCoverUploadError('上传失败，请重试');
    } finally {
      setIsUploadingCover(false);
    }
  };

  // 删除封面
  const handleDeleteCover = async () => {
    if (!isEditing || !podcast) return;

    const confirmed = await showConfirm('确定删除封面吗？');
    if (!confirmed) return;

    setIsUploadingCover(true);
    setCoverUploadError('');

    try {
      const response = await podcastsAPI.deleteCover(podcast.username, podcast.dirName);

      if (response.status === 'success') {
        onSuccess?.();
      } else {
        const errorMsg = response.status === 'error' ? response.message : '删除失败';
        setCoverUploadError(errorMsg);
      }
    } catch (error) {
      console.error('[PodcastForm] Cover delete error:', error);
      setCoverUploadError('删除失败，请重试');
    } finally {
      setIsUploadingCover(false);
    }
  };

  const onSubmit = async (data: PodcastFormData) => {
    try {
      let response;

      // 为可选字段提供默认值以匹配 API 要求
      const submitData = {
        dirName: data.dirName,
        title: data.title,
        description: data.description || '',
        author: data.author || '',
        email: data.email || '',
        category: data.category || 'Technology',
        language: data.language || 'zh-CN',
        explicit: data.explicit || false,
      };

      if (isEditing) {
        response = await podcastsAPI.update(podcast.username, podcast.dirName, submitData);
      } else {
        response = await podcastsAPI.create(submitData);
      }

      if (response.status === 'success') {
        onSuccess?.();
      } else {
        const errorMsg =
          response.status === 'error'
            ? response.message
            : JSON.stringify(response.data);
        await showAlert(`操作失败: ${errorMsg}`, '错误');
      }
    } catch (error) {
      console.error('Form submission error:', error);
      await showAlert('操作失败，请重试', '错误');
    }
  };

  return (
    <Box component="form" onSubmit={handleSubmit(onSubmit)}>
      <Stack spacing={2}>
        {/* 提示信息 */}
        {!isEditing && (
          <Alert severity="info">
            只需填写<strong>目录名称</strong>，标题会自动生成，其他信息都是可选的。上传音频后即可立即生成播客。
          </Alert>
        )}

        {/* 封面上传（仅编辑时显示） */}
        {isEditing && podcast && (
          <Box>
            <Box sx={{ mb: 1, fontSize: '0.875rem', fontWeight: 600 }}>
              播客封面（可选）
            </Box>

            {coverUploadError && (
              <Alert severity="error" sx={{ mb: 1 }}>
                {coverUploadError}
              </Alert>
            )}

            {podcast.imageUrl && (
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 1 }}>
                <Box
                  component="img"
                  src={podcast.imageUrl}
                  alt="当前封面"
                  sx={{
                    width: 64,
                    height: 64,
                    objectFit: 'cover',
                    borderRadius: 1,
                    border: '1px solid',
                    borderColor: 'divider',
                  }}
                />
                <Button
                  size="small"
                  variant="text"
                  startIcon={<Delete />}
                  onClick={handleDeleteCover}
                  disabled={isUploadingCover}
                  color="error"
                >
                  删除
                </Button>
              </Box>
            )}

            <Box>
              <input
                type="file"
                id="cover-upload"
                accept="image/jpeg,image/png,image/webp"
                onChange={handleCoverUpload}
                disabled={isUploadingCover}
                style={{ display: 'none' }}
              />
              <label htmlFor="cover-upload">
                <Button
                  component="span"
                  size="small"
                  variant="outlined"
                  startIcon={isUploadingCover ? <CircularProgress size={16} /> : <Image />}
                  disabled={isUploadingCover}
                >
                  {isUploadingCover ? '上传中...' : podcast.imageUrl ? '更换封面' : '上传封面'}
                </Button>
              </label>
              <Box sx={{ mt: 0.5, fontSize: '0.6875rem', color: 'text.secondary' }}>
                支持 JPEG、PNG、WebP 格式，最大 10MB
              </Box>
            </Box>
          </Box>
        )}

        {/* 目录名称 */}
        <Box>
          <Stack direction="row" spacing={1}>
            <TextField
              label="目录名称"
              required
              error={!!errors.dirName}
              helperText={errors.dirName?.message || "支持中文转拼音，只能包含字母、数字、下划线和连字符"}
              {...register('dirName')}
              placeholder="my-podcast"
              fullWidth
            />
            <Button
              size="small"
              variant="outlined"
              startIcon={<AutoAwesome />}
              onClick={handleAutoGenerateDirName}
              sx={{ flexShrink: 0, mt: '8px !important' }}
            >
              根据标题生成
            </Button>
          </Stack>
        </Box>

        {/* 播客标题 */}
        <TextField
          label="播客标题"
          required
          error={!!errors.title}
          helperText={errors.title?.message || "标题会自动根据目录名称生成，您也可以手动修改"}
          value={title}
          onChange={handleTitleChange}
          placeholder="我的技术播客"
          fullWidth
        />

        {/* 播客描述 */}
        <TextField
          label="播客描述（可选）"
          error={!!errors.description}
          helperText={errors.description?.message}
          {...register('description')}
          placeholder="分享技术知识和经验"
          multiline
          rows={3}
          fullWidth
        />

        {/* 作者 */}
        <TextField
          label="作者（可选）"
          error={!!errors.author}
          helperText={errors.author?.message}
          {...register('author')}
          placeholder="张三"
          fullWidth
        />

        {/* 邮箱 */}
        <TextField
          label="邮箱（可选）"
          error={!!errors.email}
          helperText={errors.email?.message}
          {...register('email')}
          type="email"
          placeholder="example@example.com"
          fullWidth
        />

        {/* 分类和语言 */}
        <Box sx={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 1.5 }}>
          <Controller
            name="category"
            control={control}
            render={({ field }) => (
              <FormControl fullWidth>
                <InputLabel>分类</InputLabel>
                <Select {...field} label="分类">
                  <MenuItem value="Technology">Technology</MenuItem>
                  <MenuItem value="Education">Education</MenuItem>
                  <MenuItem value="Business">Business</MenuItem>
                  <MenuItem value="Arts">Arts</MenuItem>
                  <MenuItem value="News">News</MenuItem>
                  <MenuItem value="Comedy">Comedy</MenuItem>
                  <MenuItem value="Music">Music</MenuItem>
                  <MenuItem value="Sports">Sports</MenuItem>
                </Select>
              </FormControl>
            )}
          />

          <Controller
            name="language"
            control={control}
            render={({ field }) => (
              <FormControl fullWidth>
                <InputLabel>语言</InputLabel>
                <Select {...field} label="语言">
                  <MenuItem value="zh-CN">中文</MenuItem>
                  <MenuItem value="en-US">English</MenuItem>
                </Select>
              </FormControl>
            )}
          />
        </Box>

        {/* Explicit */}
        <Controller
          name="explicit"
          control={control}
          render={({ field }) => (
            <FormControlLabel
              control={
                <Checkbox
                  checked={field.value}
                  onChange={(e) => field.onChange(e.target.checked)}
                />
              }
              label="包含露骨内容"
            />
          )}
        />

        {/* 按钮 */}
        <Stack direction="row" spacing={1} sx={{ mt: 1 }}>
          <Button
            type="submit"
            variant="contained"
            disabled={isSubmitting}
            fullWidth
          >
            {isSubmitting ? '提交中...' : isEditing ? '更新播客' : '创建播客'}
          </Button>
          <Button
            type="button"
            variant="outlined"
            onClick={onCancel}
          >
            取消
          </Button>
        </Stack>
      </Stack>
    </Box>
  );
}
